DOCS_ROOT = "../docs/"
GCREDS = "./creds.json"
GSPREADSHEET = "Utilities Dashboard"
BILL_QUERY = [
    'Klantnummer:\n',
    '(?P<customer_num>\d+)\nFactuurnummer:\n',
    '(?P<invoice_num>\d+)\nVervaldatum:\n',
    '(?P<due_date>[\d\-]+)[\s\S]+Termijnfactuur\s{3}',
    '(?P<month>\w*)[\s\S]+Vaste leveringskosten\n',
    '(?P<present_period>[\d]{2}\-[\d]{2} t\/m [\d]{2}\-[\d]{2})[\W]{3}',
    '(?P<del_cost_novat>(?<=€\n)[\d\,]+)[\W]{3}',
    '(?P<del_cost_wvat>(?<=€\n)[\d\,]+)[\s\S]+ODE[\w\s\-\/]+[\W]{3}',
    '(?P<ode_novat>(?<=€\n)[\d\,]+)[\W]{3}',
    '(?P<ode_wvat>(?<=€\n)[\d\,]+)\nVermindering energiebelasting[\w\s\-\/]+[\W]{3}',
    '(?P<reduc_novat>(?<=€\n)[\-\d\,]+)[\W]{3}',
    '(?P<reduc_wvat>(?<=€\n)[\-\d\,]+)\nNetbeheerkosten[\w\s\-\/]+[\W]{2}',
    '(?P<nmcost_novat>(?<=€\n)[\d\,]+)[\W]{3}',
    '(?P<nmcost_wvat>(?<=€\n)[\-\d\,]+)[\s\S]+verbruik[\w\s\-\/]+\n',
    '(?P<gas_consumption>\d+)[\W]{3}m[\s\S]{5}',
    '(?P<gas_cons_ppu>(?<=€\n)[\-\d\,]+)\W{3}',
    '(?P<gas_cons_novat>(?<=€\n)[\d\,]+)\W{3}',
    '(?P<gas_cons_wvat>(?<=€\n)[\d\,]+)[\s\S]+compensatie[\w\s\-\/]+\n',
    '(?P<gas_compensation>\d+)[\W]{3}m[\s\S]{5}',
    '(?P<gas_comp_ppu>(?<=€\n)[\-\d\,]+)\W{3}',
    '(?P<gas_comp_novat>(?<=€\n)[\-\d\,]+)\W{3}',
    '(?P<gas_comp_wvat>(?<=€\n)[\-\d\,]+)\nLeveringsadres:\n',
    '(?P<delivery_add>[\w \,\d]+)\nEAN[\W]{2}elektriciteit\n:\n',
    '(?P<EAN_el>\d+)\nEAN[\W]{2}gas\n:\n',
    '(?P<EAN_gas>\d+)[\s\S]+Incl\.[\W]{2}',
    '(?P<incl_BWT>[\d\,]+)[\W]{2}BTW[\W]{3}',
    '(?P<invoice_amt>(?<=€\n)[\d\,]+)[\s\S]+verbruik[\w\s\-\/]+\n',
    '(?P<el_consumption>\d+)[\W]{3}kWh[\W]{3}',
    '(?P<el_cons_ppu>(?<=€\n)[\-\d\,]+)',
]